import React, { createContext, useContext, useState, useEffect, type ReactNode } from "react";
import { db } from "@/firebase/firebase";
import { doc, getDoc, setDoc, onSnapshot, updateDoc, arrayUnion, arrayRemove } from "firebase/firestore";
import { useAuth } from "./auth-context";
import { useScan } from "./scan-context";
import { API_BASE_URL } from "./config";
import { toast } from "sonner";

export interface StoreOffer {
  store: string;
  price: number;
  offer: string;
  best?: boolean;
  url: string;
}

export interface Product {
  id: string;
  name: string;
  brand: string;
  category: "Skincare" | "Makeup";
  subcategory: string;
  price: number;
  rating: number;
  reviews: number;
  match: number;
  image: string;
  reason: string;
  ingredients: string[];
  benefits: string[];
  suitable: string;
  usage: string;
  stores: StoreOffer[];
}

interface ProductsContextType {
  products: Product[];
  favorites: string[];
  isLoading: boolean;
  isGenerating: boolean;
  generateRecommendations: () => Promise<void>;
  toggleFavorite: (productId: string) => Promise<void>;
}

const ProductsContext = createContext<ProductsContextType | undefined>(undefined);

export function ProductsProvider({ children }: { children: ReactNode }) {
  const { user } = useAuth();
  const { currentScan } = useScan();
  const [products, setProducts] = useState<Product[]>([]);
  const [favorites, setFavorites] = useState<string[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    if (!user?.uid) {
      setProducts([]);
      setFavorites([]);
      setIsLoading(false);
      return;
    }

    const docRef = doc(db, "users", user.uid, "products", "recommendations");
    const unsubscribe = onSnapshot(docRef, (snapshot) => {
      if (snapshot.exists()) {
        const data = snapshot.data();
        setProducts(data.items || []);
        setFavorites(data.favorites || []);
      } else {
        setProducts([]);
        setFavorites([]);
      }
      setIsLoading(false);
    });

    return () => unsubscribe();
  }, [user?.uid]);

  const generateRecommendations = async () => {
    if (!user?.uid) return;
    setIsGenerating(true);

    try {
      const apiUrl = `${API_BASE_URL}/recommend-products`;

      const response = await fetch(apiUrl, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          skinType: currentScan?.skinType || user.profile.goals.join(", "),
          concerns: currentScan?.concerns.map(c => c.label) || [],
          goals: user.profile.goals,
          allergies: user.profile.allergies,
        }),
      });

      const data = await response.json();
      
      if (data.success && data.products) {
        const docRef = doc(db, "users", user.uid, "products", "recommendations");
        await setDoc(docRef, { items: data.products }, { merge: true });
        toast.success("AI generated new product recommendations!");
      } else {
        toast.error("Failed to generate recommendations");
      }
    } catch (error) {
      console.error("[Products] Error generating products:", error);
      toast.error("An error occurred while generating recommendations.");
    } finally {
      setIsGenerating(false);
    }
  };

  // Auto-generate recommendations when a new scan is completed or if products are empty
  const autoGeneratedScanId = React.useRef<string | null>(null);
  useEffect(() => {
    // Trigger 1: A brand new scan was completed in this session
    if (currentScan && currentScan.id !== autoGeneratedScanId.current) {
      autoGeneratedScanId.current = currentScan.id;
      setTimeout(() => generateRecommendations(), 500);
    } 
    // Trigger 2: User navigates to products page and has NO recommendations yet
    else if (!isLoading && products.length === 0 && !isGenerating) {
      // Set a flag to avoid infinite loops if the generation fails and leaves products empty
      if (autoGeneratedScanId.current !== "initial-empty-trigger") {
        autoGeneratedScanId.current = "initial-empty-trigger";
        setTimeout(() => generateRecommendations(), 500);
      }
    }
  }, [currentScan, isLoading, products.length, isGenerating]);


  const toggleFavorite = async (productId: string) => {
    if (!user?.uid) {
      toast.error("Please login to save favorites");
      return;
    }

    const docRef = doc(db, "users", user.uid, "products", "recommendations");
    const isFav = favorites.includes(productId);

    try {
      if (isFav) {
        await updateDoc(docRef, { favorites: arrayRemove(productId) });
        toast.success("Removed from favorites");
      } else {
        await setDoc(docRef, { favorites: arrayUnion(productId) }, { merge: true });
        toast.success("Added to favorites");
      }
    } catch (error) {
      console.error("[Products] Error toggling favorite:", error);
      toast.error("Failed to update favorites");
    }
  };

  return (
    <ProductsContext.Provider
      value={{
        products,
        favorites,
        isLoading,
        isGenerating,
        generateRecommendations,
        toggleFavorite,
      }}
    >
      {children}
    </ProductsContext.Provider>
  );
}

export function useProducts() {
  const context = useContext(ProductsContext);
  if (context === undefined) {
    throw new Error("useProducts must be used within a ProductsProvider");
  }
  return context;
}
